package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.ObjectUser;
import greendao.ObjectDeal;
import greendao.ObjectDealOutlet;
import greendao.ObjectDealMerchant;
import greendao.Merchant;
import greendao.MerchantList;
import greendao.Outlet;
import greendao.Comment;
import greendao.MyLocation;
import greendao.Discovery;
import greendao.DealAvailable;
import greendao.DealClaimed;
import greendao.DealFilter;
import greendao.ObjectDealSearch;
import greendao.Following;
import greendao.TypeSearch;
import greendao.IndustryType;
import greendao.IndustrySearch;
import greendao.Discount;
import greendao.PermanentDeals;
import greendao.Notify;
import greendao.PhoneCode;
import greendao.Category;
import greendao.TypeDeal;
import greendao.Review;

import greendao.ObjectUserDao;
import greendao.ObjectDealDao;
import greendao.ObjectDealOutletDao;
import greendao.ObjectDealMerchantDao;
import greendao.MerchantDao;
import greendao.MerchantListDao;
import greendao.OutletDao;
import greendao.CommentDao;
import greendao.MyLocationDao;
import greendao.DiscoveryDao;
import greendao.DealAvailableDao;
import greendao.DealClaimedDao;
import greendao.DealFilterDao;
import greendao.ObjectDealSearchDao;
import greendao.FollowingDao;
import greendao.TypeSearchDao;
import greendao.IndustryTypeDao;
import greendao.IndustrySearchDao;
import greendao.DiscountDao;
import greendao.PermanentDealsDao;
import greendao.NotifyDao;
import greendao.PhoneCodeDao;
import greendao.CategoryDao;
import greendao.TypeDealDao;
import greendao.ReviewDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig objectUserDaoConfig;
    private final DaoConfig objectDealDaoConfig;
    private final DaoConfig objectDealOutletDaoConfig;
    private final DaoConfig objectDealMerchantDaoConfig;
    private final DaoConfig merchantDaoConfig;
    private final DaoConfig merchantListDaoConfig;
    private final DaoConfig outletDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig myLocationDaoConfig;
    private final DaoConfig discoveryDaoConfig;
    private final DaoConfig dealAvailableDaoConfig;
    private final DaoConfig dealClaimedDaoConfig;
    private final DaoConfig dealFilterDaoConfig;
    private final DaoConfig objectDealSearchDaoConfig;
    private final DaoConfig followingDaoConfig;
    private final DaoConfig typeSearchDaoConfig;
    private final DaoConfig industryTypeDaoConfig;
    private final DaoConfig industrySearchDaoConfig;
    private final DaoConfig discountDaoConfig;
    private final DaoConfig permanentDealsDaoConfig;
    private final DaoConfig notifyDaoConfig;
    private final DaoConfig phoneCodeDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig typeDealDaoConfig;
    private final DaoConfig reviewDaoConfig;

    private final ObjectUserDao objectUserDao;
    private final ObjectDealDao objectDealDao;
    private final ObjectDealOutletDao objectDealOutletDao;
    private final ObjectDealMerchantDao objectDealMerchantDao;
    private final MerchantDao merchantDao;
    private final MerchantListDao merchantListDao;
    private final OutletDao outletDao;
    private final CommentDao commentDao;
    private final MyLocationDao myLocationDao;
    private final DiscoveryDao discoveryDao;
    private final DealAvailableDao dealAvailableDao;
    private final DealClaimedDao dealClaimedDao;
    private final DealFilterDao dealFilterDao;
    private final ObjectDealSearchDao objectDealSearchDao;
    private final FollowingDao followingDao;
    private final TypeSearchDao typeSearchDao;
    private final IndustryTypeDao industryTypeDao;
    private final IndustrySearchDao industrySearchDao;
    private final DiscountDao discountDao;
    private final PermanentDealsDao permanentDealsDao;
    private final NotifyDao notifyDao;
    private final PhoneCodeDao phoneCodeDao;
    private final CategoryDao categoryDao;
    private final TypeDealDao typeDealDao;
    private final ReviewDao reviewDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        objectUserDaoConfig = daoConfigMap.get(ObjectUserDao.class).clone();
        objectUserDaoConfig.initIdentityScope(type);

        objectDealDaoConfig = daoConfigMap.get(ObjectDealDao.class).clone();
        objectDealDaoConfig.initIdentityScope(type);

        objectDealOutletDaoConfig = daoConfigMap.get(ObjectDealOutletDao.class).clone();
        objectDealOutletDaoConfig.initIdentityScope(type);

        objectDealMerchantDaoConfig = daoConfigMap.get(ObjectDealMerchantDao.class).clone();
        objectDealMerchantDaoConfig.initIdentityScope(type);

        merchantDaoConfig = daoConfigMap.get(MerchantDao.class).clone();
        merchantDaoConfig.initIdentityScope(type);

        merchantListDaoConfig = daoConfigMap.get(MerchantListDao.class).clone();
        merchantListDaoConfig.initIdentityScope(type);

        outletDaoConfig = daoConfigMap.get(OutletDao.class).clone();
        outletDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        myLocationDaoConfig = daoConfigMap.get(MyLocationDao.class).clone();
        myLocationDaoConfig.initIdentityScope(type);

        discoveryDaoConfig = daoConfigMap.get(DiscoveryDao.class).clone();
        discoveryDaoConfig.initIdentityScope(type);

        dealAvailableDaoConfig = daoConfigMap.get(DealAvailableDao.class).clone();
        dealAvailableDaoConfig.initIdentityScope(type);

        dealClaimedDaoConfig = daoConfigMap.get(DealClaimedDao.class).clone();
        dealClaimedDaoConfig.initIdentityScope(type);

        dealFilterDaoConfig = daoConfigMap.get(DealFilterDao.class).clone();
        dealFilterDaoConfig.initIdentityScope(type);

        objectDealSearchDaoConfig = daoConfigMap.get(ObjectDealSearchDao.class).clone();
        objectDealSearchDaoConfig.initIdentityScope(type);

        followingDaoConfig = daoConfigMap.get(FollowingDao.class).clone();
        followingDaoConfig.initIdentityScope(type);

        typeSearchDaoConfig = daoConfigMap.get(TypeSearchDao.class).clone();
        typeSearchDaoConfig.initIdentityScope(type);

        industryTypeDaoConfig = daoConfigMap.get(IndustryTypeDao.class).clone();
        industryTypeDaoConfig.initIdentityScope(type);

        industrySearchDaoConfig = daoConfigMap.get(IndustrySearchDao.class).clone();
        industrySearchDaoConfig.initIdentityScope(type);

        discountDaoConfig = daoConfigMap.get(DiscountDao.class).clone();
        discountDaoConfig.initIdentityScope(type);

        permanentDealsDaoConfig = daoConfigMap.get(PermanentDealsDao.class).clone();
        permanentDealsDaoConfig.initIdentityScope(type);

        notifyDaoConfig = daoConfigMap.get(NotifyDao.class).clone();
        notifyDaoConfig.initIdentityScope(type);

        phoneCodeDaoConfig = daoConfigMap.get(PhoneCodeDao.class).clone();
        phoneCodeDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        typeDealDaoConfig = daoConfigMap.get(TypeDealDao.class).clone();
        typeDealDaoConfig.initIdentityScope(type);

        reviewDaoConfig = daoConfigMap.get(ReviewDao.class).clone();
        reviewDaoConfig.initIdentityScope(type);

        objectUserDao = new ObjectUserDao(objectUserDaoConfig, this);
        objectDealDao = new ObjectDealDao(objectDealDaoConfig, this);
        objectDealOutletDao = new ObjectDealOutletDao(objectDealOutletDaoConfig, this);
        objectDealMerchantDao = new ObjectDealMerchantDao(objectDealMerchantDaoConfig, this);
        merchantDao = new MerchantDao(merchantDaoConfig, this);
        merchantListDao = new MerchantListDao(merchantListDaoConfig, this);
        outletDao = new OutletDao(outletDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        myLocationDao = new MyLocationDao(myLocationDaoConfig, this);
        discoveryDao = new DiscoveryDao(discoveryDaoConfig, this);
        dealAvailableDao = new DealAvailableDao(dealAvailableDaoConfig, this);
        dealClaimedDao = new DealClaimedDao(dealClaimedDaoConfig, this);
        dealFilterDao = new DealFilterDao(dealFilterDaoConfig, this);
        objectDealSearchDao = new ObjectDealSearchDao(objectDealSearchDaoConfig, this);
        followingDao = new FollowingDao(followingDaoConfig, this);
        typeSearchDao = new TypeSearchDao(typeSearchDaoConfig, this);
        industryTypeDao = new IndustryTypeDao(industryTypeDaoConfig, this);
        industrySearchDao = new IndustrySearchDao(industrySearchDaoConfig, this);
        discountDao = new DiscountDao(discountDaoConfig, this);
        permanentDealsDao = new PermanentDealsDao(permanentDealsDaoConfig, this);
        notifyDao = new NotifyDao(notifyDaoConfig, this);
        phoneCodeDao = new PhoneCodeDao(phoneCodeDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        typeDealDao = new TypeDealDao(typeDealDaoConfig, this);
        reviewDao = new ReviewDao(reviewDaoConfig, this);

        registerDao(ObjectUser.class, objectUserDao);
        registerDao(ObjectDeal.class, objectDealDao);
        registerDao(ObjectDealOutlet.class, objectDealOutletDao);
        registerDao(ObjectDealMerchant.class, objectDealMerchantDao);
        registerDao(Merchant.class, merchantDao);
        registerDao(MerchantList.class, merchantListDao);
        registerDao(Outlet.class, outletDao);
        registerDao(Comment.class, commentDao);
        registerDao(MyLocation.class, myLocationDao);
        registerDao(Discovery.class, discoveryDao);
        registerDao(DealAvailable.class, dealAvailableDao);
        registerDao(DealClaimed.class, dealClaimedDao);
        registerDao(DealFilter.class, dealFilterDao);
        registerDao(ObjectDealSearch.class, objectDealSearchDao);
        registerDao(Following.class, followingDao);
        registerDao(TypeSearch.class, typeSearchDao);
        registerDao(IndustryType.class, industryTypeDao);
        registerDao(IndustrySearch.class, industrySearchDao);
        registerDao(Discount.class, discountDao);
        registerDao(PermanentDeals.class, permanentDealsDao);
        registerDao(Notify.class, notifyDao);
        registerDao(PhoneCode.class, phoneCodeDao);
        registerDao(Category.class, categoryDao);
        registerDao(TypeDeal.class, typeDealDao);
        registerDao(Review.class, reviewDao);
    }
    
    public void clear() {
        objectUserDaoConfig.getIdentityScope().clear();
        objectDealDaoConfig.getIdentityScope().clear();
        objectDealOutletDaoConfig.getIdentityScope().clear();
        objectDealMerchantDaoConfig.getIdentityScope().clear();
        merchantDaoConfig.getIdentityScope().clear();
        merchantListDaoConfig.getIdentityScope().clear();
        outletDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        myLocationDaoConfig.getIdentityScope().clear();
        discoveryDaoConfig.getIdentityScope().clear();
        dealAvailableDaoConfig.getIdentityScope().clear();
        dealClaimedDaoConfig.getIdentityScope().clear();
        dealFilterDaoConfig.getIdentityScope().clear();
        objectDealSearchDaoConfig.getIdentityScope().clear();
        followingDaoConfig.getIdentityScope().clear();
        typeSearchDaoConfig.getIdentityScope().clear();
        industryTypeDaoConfig.getIdentityScope().clear();
        industrySearchDaoConfig.getIdentityScope().clear();
        discountDaoConfig.getIdentityScope().clear();
        permanentDealsDaoConfig.getIdentityScope().clear();
        notifyDaoConfig.getIdentityScope().clear();
        phoneCodeDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        typeDealDaoConfig.getIdentityScope().clear();
        reviewDaoConfig.getIdentityScope().clear();
    }

    public ObjectUserDao getObjectUserDao() {
        return objectUserDao;
    }

    public ObjectDealDao getObjectDealDao() {
        return objectDealDao;
    }

    public ObjectDealOutletDao getObjectDealOutletDao() {
        return objectDealOutletDao;
    }

    public ObjectDealMerchantDao getObjectDealMerchantDao() {
        return objectDealMerchantDao;
    }

    public MerchantDao getMerchantDao() {
        return merchantDao;
    }

    public MerchantListDao getMerchantListDao() {
        return merchantListDao;
    }

    public OutletDao getOutletDao() {
        return outletDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public MyLocationDao getMyLocationDao() {
        return myLocationDao;
    }

    public DiscoveryDao getDiscoveryDao() {
        return discoveryDao;
    }

    public DealAvailableDao getDealAvailableDao() {
        return dealAvailableDao;
    }

    public DealClaimedDao getDealClaimedDao() {
        return dealClaimedDao;
    }

    public DealFilterDao getDealFilterDao() {
        return dealFilterDao;
    }

    public ObjectDealSearchDao getObjectDealSearchDao() {
        return objectDealSearchDao;
    }

    public FollowingDao getFollowingDao() {
        return followingDao;
    }

    public TypeSearchDao getTypeSearchDao() {
        return typeSearchDao;
    }

    public IndustryTypeDao getIndustryTypeDao() {
        return industryTypeDao;
    }

    public IndustrySearchDao getIndustrySearchDao() {
        return industrySearchDao;
    }

    public DiscountDao getDiscountDao() {
        return discountDao;
    }

    public PermanentDealsDao getPermanentDealsDao() {
        return permanentDealsDao;
    }

    public NotifyDao getNotifyDao() {
        return notifyDao;
    }

    public PhoneCodeDao getPhoneCodeDao() {
        return phoneCodeDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public TypeDealDao getTypeDealDao() {
        return typeDealDao;
    }

    public ReviewDao getReviewDao() {
        return reviewDao;
    }

}
