package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEAL_FILTER.
 */
public class DealFilter {

    private Long id;
    private String purchase_type;
    private Long distance;
    private String industry_type;
    private String keyword;

    public DealFilter() {
    }

    public DealFilter(Long id) {
        this.id = id;
    }

    public DealFilter(Long id, String purchase_type, Long distance, String industry_type, String keyword) {
        this.id = id;
        this.purchase_type = purchase_type;
        this.distance = distance;
        this.industry_type = industry_type;
        this.keyword = keyword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPurchase_type() {
        return purchase_type;
    }

    public void setPurchase_type(String purchase_type) {
        this.purchase_type = purchase_type;
    }

    public Long getDistance() {
        return distance;
    }

    public void setDistance(Long distance) {
        this.distance = distance;
    }

    public String getIndustry_type() {
        return industry_type;
    }

    public void setIndustry_type(String industry_type) {
        this.industry_type = industry_type;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

}
