package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEAL_CLAIMED.
 */
public class DealClaimed {

    private Long deal_id;
    private String title;
    private String created_at;
    private String consumed_at;
    private Long merchant_id;
    private String organization_name;
    private String validity;
    private Boolean f_claimed;

    public DealClaimed() {
    }

    public DealClaimed(Long deal_id) {
        this.deal_id = deal_id;
    }

    public DealClaimed(Long deal_id, String title, String created_at, String consumed_at, Long merchant_id, String organization_name, String validity, Boolean f_claimed) {
        this.deal_id = deal_id;
        this.title = title;
        this.created_at = created_at;
        this.consumed_at = consumed_at;
        this.merchant_id = merchant_id;
        this.organization_name = organization_name;
        this.validity = validity;
        this.f_claimed = f_claimed;
    }

    public Long getDeal_id() {
        return deal_id;
    }

    public void setDeal_id(Long deal_id) {
        this.deal_id = deal_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getConsumed_at() {
        return consumed_at;
    }

    public void setConsumed_at(String consumed_at) {
        this.consumed_at = consumed_at;
    }

    public Long getMerchant_id() {
        return merchant_id;
    }

    public void setMerchant_id(Long merchant_id) {
        this.merchant_id = merchant_id;
    }

    public String getOrganization_name() {
        return organization_name;
    }

    public void setOrganization_name(String organization_name) {
        this.organization_name = organization_name;
    }

    public String getValidity() {
        return validity;
    }

    public void setValidity(String validity) {
        this.validity = validity;
    }

    public Boolean getF_claimed() {
        return f_claimed;
    }

    public void setF_claimed(Boolean f_claimed) {
        this.f_claimed = f_claimed;
    }

}
