package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DISCOUNT.
 */
public class Discount {

    private Long id;
    private String code;
    private Float amount;
    private String note;
    private String created_at;

    public Discount() {
    }

    public Discount(Long id) {
        this.id = id;
    }

    public Discount(Long id, String code, Float amount, String note, String created_at) {
        this.id = id;
        this.code = code;
        this.amount = amount;
        this.note = note;
        this.created_at = created_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

}
