package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INDUSTRY_TYPE.
 */
public class IndustryType {

    private Long id;
    private String name;

    public IndustryType() {
    }

    public IndustryType(Long id) {
        this.id = id;
    }

    public IndustryType(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
