package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MERCHANT.
 */
public class Merchant {

    private Long merchant_id;
    private String first_name;
    private String last_name;
    private String organization_name;
    private Integer industry_type_id;
    private String phone;
    private String tags;
    private String logo_image;
    private Integer k_follows;
    private Integer k_likes;
    private Integer k_unlikes;
    private Integer k_outlets;
    private Boolean f_yay;
    private Boolean f_nay;
    private Boolean f_follow;
    private String profile_images;
    private Integer live_deals;
    private Integer past_deals;
    private String website_url;
    private String facebook_url;
    private String twitter_url;
    private String instagram_url;
    private String description;
    private String cover_image;

    public Merchant() {
    }

    public Merchant(Long merchant_id) {
        this.merchant_id = merchant_id;
    }

    public Merchant(Long merchant_id, String first_name, String last_name, String organization_name, Integer industry_type_id, String phone, String tags, String logo_image, Integer k_follows, Integer k_likes, Integer k_unlikes, Integer k_outlets, Boolean f_yay, Boolean f_nay, Boolean f_follow, String profile_images, Integer live_deals, Integer past_deals, String website_url, String facebook_url, String twitter_url, String instagram_url, String description, String cover_image) {
        this.merchant_id = merchant_id;
        this.first_name = first_name;
        this.last_name = last_name;
        this.organization_name = organization_name;
        this.industry_type_id = industry_type_id;
        this.phone = phone;
        this.tags = tags;
        this.logo_image = logo_image;
        this.k_follows = k_follows;
        this.k_likes = k_likes;
        this.k_unlikes = k_unlikes;
        this.k_outlets = k_outlets;
        this.f_yay = f_yay;
        this.f_nay = f_nay;
        this.f_follow = f_follow;
        this.profile_images = profile_images;
        this.live_deals = live_deals;
        this.past_deals = past_deals;
        this.website_url = website_url;
        this.facebook_url = facebook_url;
        this.twitter_url = twitter_url;
        this.instagram_url = instagram_url;
        this.description = description;
        this.cover_image = cover_image;
    }

    public Long getMerchant_id() {
        return merchant_id;
    }

    public void setMerchant_id(Long merchant_id) {
        this.merchant_id = merchant_id;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String getOrganization_name() {
        return organization_name;
    }

    public void setOrganization_name(String organization_name) {
        this.organization_name = organization_name;
    }

    public Integer getIndustry_type_id() {
        return industry_type_id;
    }

    public void setIndustry_type_id(Integer industry_type_id) {
        this.industry_type_id = industry_type_id;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getLogo_image() {
        return logo_image;
    }

    public void setLogo_image(String logo_image) {
        this.logo_image = logo_image;
    }

    public Integer getK_follows() {
        return k_follows;
    }

    public void setK_follows(Integer k_follows) {
        this.k_follows = k_follows;
    }

    public Integer getK_likes() {
        return k_likes;
    }

    public void setK_likes(Integer k_likes) {
        this.k_likes = k_likes;
    }

    public Integer getK_unlikes() {
        return k_unlikes;
    }

    public void setK_unlikes(Integer k_unlikes) {
        this.k_unlikes = k_unlikes;
    }

    public Integer getK_outlets() {
        return k_outlets;
    }

    public void setK_outlets(Integer k_outlets) {
        this.k_outlets = k_outlets;
    }

    public Boolean getF_yay() {
        return f_yay;
    }

    public void setF_yay(Boolean f_yay) {
        this.f_yay = f_yay;
    }

    public Boolean getF_nay() {
        return f_nay;
    }

    public void setF_nay(Boolean f_nay) {
        this.f_nay = f_nay;
    }

    public Boolean getF_follow() {
        return f_follow;
    }

    public void setF_follow(Boolean f_follow) {
        this.f_follow = f_follow;
    }

    public String getProfile_images() {
        return profile_images;
    }

    public void setProfile_images(String profile_images) {
        this.profile_images = profile_images;
    }

    public Integer getLive_deals() {
        return live_deals;
    }

    public void setLive_deals(Integer live_deals) {
        this.live_deals = live_deals;
    }

    public Integer getPast_deals() {
        return past_deals;
    }

    public void setPast_deals(Integer past_deals) {
        this.past_deals = past_deals;
    }

    public String getWebsite_url() {
        return website_url;
    }

    public void setWebsite_url(String website_url) {
        this.website_url = website_url;
    }

    public String getFacebook_url() {
        return facebook_url;
    }

    public void setFacebook_url(String facebook_url) {
        this.facebook_url = facebook_url;
    }

    public String getTwitter_url() {
        return twitter_url;
    }

    public void setTwitter_url(String twitter_url) {
        this.twitter_url = twitter_url;
    }

    public String getInstagram_url() {
        return instagram_url;
    }

    public void setInstagram_url(String instagram_url) {
        this.instagram_url = instagram_url;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCover_image() {
        return cover_image;
    }

    public void setCover_image(String cover_image) {
        this.cover_image = cover_image;
    }

}
