package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTIFY.
 */
public class Notify {

    private Long deal_id;

    public Notify() {
    }

    public Notify(Long deal_id) {
        this.deal_id = deal_id;
    }

    public Long getDeal_id() {
        return deal_id;
    }

    public void setDeal_id(Long deal_id) {
        this.deal_id = deal_id;
    }

}
