package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_DEAL_SEARCH.
 */
public class ObjectDealSearch {

    private Long id;
    private Long deal_id;
    private String image;
    private String title;
    private String type;
    private String start_at;
    private String end_at;
    private Integer max_claim;
    private Float original_price;
    private Float purchase_now_price;
    private Long outlet_id;
    private Long merchant_id;
    private Integer is_longterm;
    private String description;
    private String terms;
    private Boolean f_claimed;
    private Boolean f_call_dibs;

    public ObjectDealSearch() {
    }

    public ObjectDealSearch(Long id) {
        this.id = id;
    }

    public ObjectDealSearch(Long id, Long deal_id, String image, String title, String type, String start_at, String end_at, Integer max_claim, Float original_price, Float purchase_now_price, Long outlet_id, Long merchant_id, Integer is_longterm, String description, String terms, Boolean f_claimed, Boolean f_call_dibs) {
        this.id = id;
        this.deal_id = deal_id;
        this.image = image;
        this.title = title;
        this.type = type;
        this.start_at = start_at;
        this.end_at = end_at;
        this.max_claim = max_claim;
        this.original_price = original_price;
        this.purchase_now_price = purchase_now_price;
        this.outlet_id = outlet_id;
        this.merchant_id = merchant_id;
        this.is_longterm = is_longterm;
        this.description = description;
        this.terms = terms;
        this.f_claimed = f_claimed;
        this.f_call_dibs = f_call_dibs;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDeal_id() {
        return deal_id;
    }

    public void setDeal_id(Long deal_id) {
        this.deal_id = deal_id;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStart_at() {
        return start_at;
    }

    public void setStart_at(String start_at) {
        this.start_at = start_at;
    }

    public String getEnd_at() {
        return end_at;
    }

    public void setEnd_at(String end_at) {
        this.end_at = end_at;
    }

    public Integer getMax_claim() {
        return max_claim;
    }

    public void setMax_claim(Integer max_claim) {
        this.max_claim = max_claim;
    }

    public Float getOriginal_price() {
        return original_price;
    }

    public void setOriginal_price(Float original_price) {
        this.original_price = original_price;
    }

    public Float getPurchase_now_price() {
        return purchase_now_price;
    }

    public void setPurchase_now_price(Float purchase_now_price) {
        this.purchase_now_price = purchase_now_price;
    }

    public Long getOutlet_id() {
        return outlet_id;
    }

    public void setOutlet_id(Long outlet_id) {
        this.outlet_id = outlet_id;
    }

    public Long getMerchant_id() {
        return merchant_id;
    }

    public void setMerchant_id(Long merchant_id) {
        this.merchant_id = merchant_id;
    }

    public Integer getIs_longterm() {
        return is_longterm;
    }

    public void setIs_longterm(Integer is_longterm) {
        this.is_longterm = is_longterm;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTerms() {
        return terms;
    }

    public void setTerms(String terms) {
        this.terms = terms;
    }

    public Boolean getF_claimed() {
        return f_claimed;
    }

    public void setF_claimed(Boolean f_claimed) {
        this.f_claimed = f_claimed;
    }

    public Boolean getF_call_dibs() {
        return f_call_dibs;
    }

    public void setF_call_dibs(Boolean f_call_dibs) {
        this.f_call_dibs = f_call_dibs;
    }

}
