package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_USER.
 */
public class ObjectUser {

    private Long user_id;
    private Long group_id;
    private String email;
    private Boolean isConsumer;
    private Long consumer_id;
    private String first_name;
    private String last_name;
    private String phone;
    private String phoneCode;
    private String gender;
    private String profile_image;
    private String facebook_id;
    private String dob;
    private Integer k_following;
    private Integer k_call_dibs;
    private String full_name;
    private String ref_code;
    private Integer f_verified_phone;
    private Integer k_ref_bonus;
    private Integer k_ref_user;
    private Integer f_valid;

    public ObjectUser() {
    }

    public ObjectUser(Long user_id) {
        this.user_id = user_id;
    }

    public ObjectUser(Long user_id, Long group_id, String email, Boolean isConsumer, Long consumer_id, String first_name, String last_name, String phone, String phoneCode, String gender, String profile_image, String facebook_id, String dob, Integer k_following, Integer k_call_dibs, String full_name, String ref_code, Integer f_verified_phone, Integer k_ref_bonus, Integer k_ref_user, Integer f_valid) {
        this.user_id = user_id;
        this.group_id = group_id;
        this.email = email;
        this.isConsumer = isConsumer;
        this.consumer_id = consumer_id;
        this.first_name = first_name;
        this.last_name = last_name;
        this.phone = phone;
        this.phoneCode = phoneCode;
        this.gender = gender;
        this.profile_image = profile_image;
        this.facebook_id = facebook_id;
        this.dob = dob;
        this.k_following = k_following;
        this.k_call_dibs = k_call_dibs;
        this.full_name = full_name;
        this.ref_code = ref_code;
        this.f_verified_phone = f_verified_phone;
        this.k_ref_bonus = k_ref_bonus;
        this.k_ref_user = k_ref_user;
        this.f_valid = f_valid;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public Long getGroup_id() {
        return group_id;
    }

    public void setGroup_id(Long group_id) {
        this.group_id = group_id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getIsConsumer() {
        return isConsumer;
    }

    public void setIsConsumer(Boolean isConsumer) {
        this.isConsumer = isConsumer;
    }

    public Long getConsumer_id() {
        return consumer_id;
    }

    public void setConsumer_id(Long consumer_id) {
        this.consumer_id = consumer_id;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoneCode() {
        return phoneCode;
    }

    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getProfile_image() {
        return profile_image;
    }

    public void setProfile_image(String profile_image) {
        this.profile_image = profile_image;
    }

    public String getFacebook_id() {
        return facebook_id;
    }

    public void setFacebook_id(String facebook_id) {
        this.facebook_id = facebook_id;
    }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public Integer getK_following() {
        return k_following;
    }

    public void setK_following(Integer k_following) {
        this.k_following = k_following;
    }

    public Integer getK_call_dibs() {
        return k_call_dibs;
    }

    public void setK_call_dibs(Integer k_call_dibs) {
        this.k_call_dibs = k_call_dibs;
    }

    public String getFull_name() {
        return full_name;
    }

    public void setFull_name(String full_name) {
        this.full_name = full_name;
    }

    public String getRef_code() {
        return ref_code;
    }

    public void setRef_code(String ref_code) {
        this.ref_code = ref_code;
    }

    public Integer getF_verified_phone() {
        return f_verified_phone;
    }

    public void setF_verified_phone(Integer f_verified_phone) {
        this.f_verified_phone = f_verified_phone;
    }

    public Integer getK_ref_bonus() {
        return k_ref_bonus;
    }

    public void setK_ref_bonus(Integer k_ref_bonus) {
        this.k_ref_bonus = k_ref_bonus;
    }

    public Integer getK_ref_user() {
        return k_ref_user;
    }

    public void setK_ref_user(Integer k_ref_user) {
        this.k_ref_user = k_ref_user;
    }

    public Integer getF_valid() {
        return f_valid;
    }

    public void setF_valid(Integer f_valid) {
        this.f_valid = f_valid;
    }

}
