package greendao;

import java.util.List;
import greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_DEAL.
 */
public class ObjectDeal {

    private Long id;
    private Long deal_id;
    private String image;
    private String image_thumbnail;
    private String title;
    private String type;
    private String start_at;
    private String end_at;
    private Integer max_claim;
    private Float original_price;
    private Float purchase_now_price;
    private Long outlet_id;
    private Long merchant_id;
    private Integer deal_type;
    private String description;
    private String terms;
    private Boolean f_claimed;
    private Boolean f_call_dibs;
    private String duration_type;
    private Integer k_rest_claim;
    private String outlets;
    private Integer k_likes;
    private Integer k_unlikes;
    private Boolean f_yay;
    private Boolean f_nay;
    private String claim_validity;
    private String organization_name;
    private Boolean is_exclusive;
    private Integer k_deals_by_outlet;
    private String refer_deal_ids;
    private Boolean f_liked;
    private String logo_image_url;
    private Long ref_merchant_id;
    private Boolean fromDealFollowing;
    private String uuid;
    private Integer group_id;
    private String group_name;
    private Long dealReferId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ObjectDealDao myDao;

    private List<ObjectDeal> refer_deal_infos;

    public ObjectDeal() {
    }

    public ObjectDeal(Long id) {
        this.id = id;
    }

    public ObjectDeal(Long id, Long deal_id, String image, String image_thumbnail, String title, String type, String start_at, String end_at, Integer max_claim, Float original_price, Float purchase_now_price, Long outlet_id, Long merchant_id, Integer deal_type, String description, String terms, Boolean f_claimed, Boolean f_call_dibs, String duration_type, Integer k_rest_claim, String outlets, Integer k_likes, Integer k_unlikes, Boolean f_yay, Boolean f_nay, String claim_validity, String organization_name, Boolean is_exclusive, Integer k_deals_by_outlet, String refer_deal_ids, Boolean f_liked, String logo_image_url, Long ref_merchant_id, Boolean fromDealFollowing, String uuid, Integer group_id, String group_name, Long dealReferId) {
        this.id = id;
        this.deal_id = deal_id;
        this.image = image;
        this.image_thumbnail = image_thumbnail;
        this.title = title;
        this.type = type;
        this.start_at = start_at;
        this.end_at = end_at;
        this.max_claim = max_claim;
        this.original_price = original_price;
        this.purchase_now_price = purchase_now_price;
        this.outlet_id = outlet_id;
        this.merchant_id = merchant_id;
        this.deal_type = deal_type;
        this.description = description;
        this.terms = terms;
        this.f_claimed = f_claimed;
        this.f_call_dibs = f_call_dibs;
        this.duration_type = duration_type;
        this.k_rest_claim = k_rest_claim;
        this.outlets = outlets;
        this.k_likes = k_likes;
        this.k_unlikes = k_unlikes;
        this.f_yay = f_yay;
        this.f_nay = f_nay;
        this.claim_validity = claim_validity;
        this.organization_name = organization_name;
        this.is_exclusive = is_exclusive;
        this.k_deals_by_outlet = k_deals_by_outlet;
        this.refer_deal_ids = refer_deal_ids;
        this.f_liked = f_liked;
        this.logo_image_url = logo_image_url;
        this.ref_merchant_id = ref_merchant_id;
        this.fromDealFollowing = fromDealFollowing;
        this.uuid = uuid;
        this.group_id = group_id;
        this.group_name = group_name;
        this.dealReferId = dealReferId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getObjectDealDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDeal_id() {
        return deal_id;
    }

    public void setDeal_id(Long deal_id) {
        this.deal_id = deal_id;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getImage_thumbnail() {
        return image_thumbnail;
    }

    public void setImage_thumbnail(String image_thumbnail) {
        this.image_thumbnail = image_thumbnail;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStart_at() {
        return start_at;
    }

    public void setStart_at(String start_at) {
        this.start_at = start_at;
    }

    public String getEnd_at() {
        return end_at;
    }

    public void setEnd_at(String end_at) {
        this.end_at = end_at;
    }

    public Integer getMax_claim() {
        return max_claim;
    }

    public void setMax_claim(Integer max_claim) {
        this.max_claim = max_claim;
    }

    public Float getOriginal_price() {
        return original_price;
    }

    public void setOriginal_price(Float original_price) {
        this.original_price = original_price;
    }

    public Float getPurchase_now_price() {
        return purchase_now_price;
    }

    public void setPurchase_now_price(Float purchase_now_price) {
        this.purchase_now_price = purchase_now_price;
    }

    public Long getOutlet_id() {
        return outlet_id;
    }

    public void setOutlet_id(Long outlet_id) {
        this.outlet_id = outlet_id;
    }

    public Long getMerchant_id() {
        return merchant_id;
    }

    public void setMerchant_id(Long merchant_id) {
        this.merchant_id = merchant_id;
    }

    public Integer getDeal_type() {
        return deal_type;
    }

    public void setDeal_type(Integer deal_type) {
        this.deal_type = deal_type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTerms() {
        return terms;
    }

    public void setTerms(String terms) {
        this.terms = terms;
    }

    public Boolean getF_claimed() {
        return f_claimed;
    }

    public void setF_claimed(Boolean f_claimed) {
        this.f_claimed = f_claimed;
    }

    public Boolean getF_call_dibs() {
        return f_call_dibs;
    }

    public void setF_call_dibs(Boolean f_call_dibs) {
        this.f_call_dibs = f_call_dibs;
    }

    public String getDuration_type() {
        return duration_type;
    }

    public void setDuration_type(String duration_type) {
        this.duration_type = duration_type;
    }

    public Integer getK_rest_claim() {
        return k_rest_claim;
    }

    public void setK_rest_claim(Integer k_rest_claim) {
        this.k_rest_claim = k_rest_claim;
    }

    public String getOutlets() {
        return outlets;
    }

    public void setOutlets(String outlets) {
        this.outlets = outlets;
    }

    public Integer getK_likes() {
        return k_likes;
    }

    public void setK_likes(Integer k_likes) {
        this.k_likes = k_likes;
    }

    public Integer getK_unlikes() {
        return k_unlikes;
    }

    public void setK_unlikes(Integer k_unlikes) {
        this.k_unlikes = k_unlikes;
    }

    public Boolean getF_yay() {
        return f_yay;
    }

    public void setF_yay(Boolean f_yay) {
        this.f_yay = f_yay;
    }

    public Boolean getF_nay() {
        return f_nay;
    }

    public void setF_nay(Boolean f_nay) {
        this.f_nay = f_nay;
    }

    public String getClaim_validity() {
        return claim_validity;
    }

    public void setClaim_validity(String claim_validity) {
        this.claim_validity = claim_validity;
    }

    public String getOrganization_name() {
        return organization_name;
    }

    public void setOrganization_name(String organization_name) {
        this.organization_name = organization_name;
    }

    public Boolean getIs_exclusive() {
        return is_exclusive;
    }

    public void setIs_exclusive(Boolean is_exclusive) {
        this.is_exclusive = is_exclusive;
    }

    public Integer getK_deals_by_outlet() {
        return k_deals_by_outlet;
    }

    public void setK_deals_by_outlet(Integer k_deals_by_outlet) {
        this.k_deals_by_outlet = k_deals_by_outlet;
    }

    public String getRefer_deal_ids() {
        return refer_deal_ids;
    }

    public void setRefer_deal_ids(String refer_deal_ids) {
        this.refer_deal_ids = refer_deal_ids;
    }

    public Boolean getF_liked() {
        return f_liked;
    }

    public void setF_liked(Boolean f_liked) {
        this.f_liked = f_liked;
    }

    public String getLogo_image_url() {
        return logo_image_url;
    }

    public void setLogo_image_url(String logo_image_url) {
        this.logo_image_url = logo_image_url;
    }

    public Long getRef_merchant_id() {
        return ref_merchant_id;
    }

    public void setRef_merchant_id(Long ref_merchant_id) {
        this.ref_merchant_id = ref_merchant_id;
    }

    public Boolean getFromDealFollowing() {
        return fromDealFollowing;
    }

    public void setFromDealFollowing(Boolean fromDealFollowing) {
        this.fromDealFollowing = fromDealFollowing;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Integer getGroup_id() {
        return group_id;
    }

    public void setGroup_id(Integer group_id) {
        this.group_id = group_id;
    }

    public String getGroup_name() {
        return group_name;
    }

    public void setGroup_name(String group_name) {
        this.group_name = group_name;
    }

    public Long getDealReferId() {
        return dealReferId;
    }

    public void setDealReferId(Long dealReferId) {
        this.dealReferId = dealReferId;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ObjectDeal> getRefer_deal_infos() {
        if (refer_deal_infos == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ObjectDealDao targetDao = daoSession.getObjectDealDao();
            List<ObjectDeal> refer_deal_infosNew = targetDao._queryObjectDeal_Refer_deal_infos(id);
            synchronized (this) {
                if(refer_deal_infos == null) {
                    refer_deal_infos = refer_deal_infosNew;
                }
            }
        }
        return refer_deal_infos;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetRefer_deal_infos() {
        refer_deal_infos = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
