package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_DEAL_MERCHANT.
 */
public class ObjectDealMerchant {

    private Long id;
    private Long merchant_id;
    private Long deal_id;
    private String organization_name;
    private String logo_image_url;

    public ObjectDealMerchant() {
    }

    public ObjectDealMerchant(Long id) {
        this.id = id;
    }

    public ObjectDealMerchant(Long id, Long merchant_id, Long deal_id, String organization_name, String logo_image_url) {
        this.id = id;
        this.merchant_id = merchant_id;
        this.deal_id = deal_id;
        this.organization_name = organization_name;
        this.logo_image_url = logo_image_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMerchant_id() {
        return merchant_id;
    }

    public void setMerchant_id(Long merchant_id) {
        this.merchant_id = merchant_id;
    }

    public Long getDeal_id() {
        return deal_id;
    }

    public void setDeal_id(Long deal_id) {
        this.deal_id = deal_id;
    }

    public String getOrganization_name() {
        return organization_name;
    }

    public void setOrganization_name(String organization_name) {
        this.organization_name = organization_name;
    }

    public String getLogo_image_url() {
        return logo_image_url;
    }

    public void setLogo_image_url(String logo_image_url) {
        this.logo_image_url = logo_image_url;
    }

}
