package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OUTLET.
 */
public class Outlet {

    private Long outlet_id;
    private Long merchant_id;
    private String name;
    private String phone;
    private String address1;
    private String address2;
    private String zip_code;
    private String latitude;
    private String longitude;
    private String secret_code;

    public Outlet() {
    }

    public Outlet(Long outlet_id) {
        this.outlet_id = outlet_id;
    }

    public Outlet(Long outlet_id, Long merchant_id, String name, String phone, String address1, String address2, String zip_code, String latitude, String longitude, String secret_code) {
        this.outlet_id = outlet_id;
        this.merchant_id = merchant_id;
        this.name = name;
        this.phone = phone;
        this.address1 = address1;
        this.address2 = address2;
        this.zip_code = zip_code;
        this.latitude = latitude;
        this.longitude = longitude;
        this.secret_code = secret_code;
    }

    public Long getOutlet_id() {
        return outlet_id;
    }

    public void setOutlet_id(Long outlet_id) {
        this.outlet_id = outlet_id;
    }

    public Long getMerchant_id() {
        return merchant_id;
    }

    public void setMerchant_id(Long merchant_id) {
        this.merchant_id = merchant_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getZip_code() {
        return zip_code;
    }

    public void setZip_code(String zip_code) {
        this.zip_code = zip_code;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getSecret_code() {
        return secret_code;
    }

    public void setSecret_code(String secret_code) {
        this.secret_code = secret_code;
    }

}
