package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PHONE_CODE.
 */
public class PhoneCode {

    private Integer id;
    private String code;
    private String name;
    private String dial_code;
    private String f_disabled;

    public PhoneCode() {
    }

    public PhoneCode(Integer id, String code, String name, String dial_code, String f_disabled) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.dial_code = dial_code;
        this.f_disabled = f_disabled;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDial_code() {
        return dial_code;
    }

    public void setDial_code(String dial_code) {
        this.dial_code = dial_code;
    }

    public String getF_disabled() {
        return f_disabled;
    }

    public void setF_disabled(String f_disabled) {
        this.f_disabled = f_disabled;
    }

}
