package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REVIEW.
 */
public class Review {

    private Long id;
    private Long review_id;
    private Long consumer_id;
    private Long deal_id;
    private Long merchant_id;
    private String review;
    private Boolean is_yay;
    private String created_at;
    private String updated_at;
    private String fullname;
    private String profile_image;

    public Review() {
    }

    public Review(Long id) {
        this.id = id;
    }

    public Review(Long id, Long review_id, Long consumer_id, Long deal_id, Long merchant_id, String review, Boolean is_yay, String created_at, String updated_at, String fullname, String profile_image) {
        this.id = id;
        this.review_id = review_id;
        this.consumer_id = consumer_id;
        this.deal_id = deal_id;
        this.merchant_id = merchant_id;
        this.review = review;
        this.is_yay = is_yay;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.fullname = fullname;
        this.profile_image = profile_image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getReview_id() {
        return review_id;
    }

    public void setReview_id(Long review_id) {
        this.review_id = review_id;
    }

    public Long getConsumer_id() {
        return consumer_id;
    }

    public void setConsumer_id(Long consumer_id) {
        this.consumer_id = consumer_id;
    }

    public Long getDeal_id() {
        return deal_id;
    }

    public void setDeal_id(Long deal_id) {
        this.deal_id = deal_id;
    }

    public Long getMerchant_id() {
        return merchant_id;
    }

    public void setMerchant_id(Long merchant_id) {
        this.merchant_id = merchant_id;
    }

    public String getReview() {
        return review;
    }

    public void setReview(String review) {
        this.review = review;
    }

    public Boolean getIs_yay() {
        return is_yay;
    }

    public void setIs_yay(Boolean is_yay) {
        this.is_yay = is_yay;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getProfile_image() {
        return profile_image;
    }

    public void setProfile_image(String profile_image) {
        this.profile_image = profile_image;
    }

}
