package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table TEMP_DEAL_MERCHANT.
 */
public class TempDealMerchant {

    private Long deal_id;

    public TempDealMerchant() {
    }

    public TempDealMerchant(Long deal_id) {
        this.deal_id = deal_id;
    }

    public Long getDeal_id() {
        return deal_id;
    }

    public void setDeal_id(Long deal_id) {
        this.deal_id = deal_id;
    }

}
