package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table TEMP_DEAL_DISCOVERY.
 */
public class TempDealDiscovery {

    private Long deal_id;

    public TempDealDiscovery() {
    }

    public TempDealDiscovery(Long deal_id) {
        this.deal_id = deal_id;
    }

    public Long getDeal_id() {
        return deal_id;
    }

    public void setDeal_id(Long deal_id) {
        this.deal_id = deal_id;
    }

}
